language: node_js
node_js:
  - '11.1.0'

sudo: false

addons:
  sauce_connect: true
install:
  - npm install -g nightwatch
  - npm install -g yarn
  - yarn install --force

cache:
  timeout: 600
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

before_script:
  - node server.js &

script:
  - npm run testCI
  - env
  - nightwatch --env chrome
  - pkill node
