language: node_js
node_js:
  - '11.1.0'

addons:
  sauce_connect: true
install:
  - npm install -g nightwatch

sudo: false

cache:
  yarn: false
  directories:
    - '.eslintcache'
    - 'node_modules'

before_script:
  - node server.js &

script:
  - npm run testCI
  - nightwatch --env chrome
  - pkill node
