language: node_js
node_js:
  - '11'

addons:
  sauce_connect: true
install:
  - npm install -g nightwatch

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

before_script:
  - node server.js

script:
  - yarn testCI
  - nightwatch --env chrome,ie11
  - pkill node
